# Generated by Django 3.1 on 2020-09-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
